### ISSUE TITLE
Transfer to personal / other account?

### ISSUE THREAD

**Issue by maelle** [traitecoevo/datastorr#23]
:wave: @wcornwell @mwpennell @dfalster @richfitz! according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by wcornwell** [comment]
Could transfer to traitecoevo org?  What do you think @richfitz?

**Comment by dfalster** [comment]
Thanks @maelle 

There's already a fork on [traitecoevo](https://github.com/traitecoevo/datastorr), so happy to store it there. 

Actually this a timely point to discuss the future of datastorr. 

Actually this a timely point to discuss the future of datastorr. We made some changes on the traitecoevo branch, to enable releases to have multiple forks, and added some testing. (This was all completed by @FabriceSamonte). 

Moving forward, big questions for me are:

1. Can we get datastorr onto cran?
2. Is there a big difference in functionality to [piggyback](https://github.com/ropensci/piggyback)? should we shift our usage and efforts there if this isn't going to be developed any further?

**Comment by cboettig** [comment]
Just chiming in with my 2c here.  I think there's definitely some things that `datastorr` covers that `piggyback` does not.  Also @rstudio's `pins` operates in this space (i.e. versioned data sets on GitHub and other backends), though maybe similarly in developer limbo at this point (?).  I think all of these packages work around different edges of this space but I think none of them provide the same level of really nice abstractions that we already have for, say, for relational database interfaces via abstractions such as DBI and dplyr.  (For example, `pins` provides a nice illustration of doing the same abstract 'board' concept with a variety of backends, like S3 or GitHub or Kaggle, but under the hood it's just custom code, sometimes rather fragile. There's not much shared between, say, `pins` notion of a GitHub board and a `piggyback` or `datastorr` notion, there's no interoperable abstraction of how we refer to content.

I think it's certainly possible to create that abstraction in an interoperable way that would make it easier for code to say "read these precise bits and bytes" while being agnostic as to whether those bytes come from a local file, a GitHub repo, or a DOI-granting repository.  With such an abstraction in place, you can make a cleaner, more extensible model for a package or ecosystem of packages to access data files from arbitrary stores.

A starting point for this would I think be to focus explicitly on data in 'files', instead of supporting both 'serialized R objects' and files.  Any specific file object could be referred to using their cryptographic hash, which acts like a DOI for each file, without any of the hassle of getting a DOI, e.g. the hash can be 'resolved' to any location that has a file matching said hash.  By itself this doesn't do anything that `datastorr` does, there's still a metadata layer to be defined mapping human friendly labels for "series" of data like "mydata" v1.0 to specific data objects, or handle mechanics of moving data around to sources like GitHub, S3, or Zenodo, but it is easy to layer those on top.  For example, software can easily determine if content can be found at a given provider by querying if the provider has anything matching said hash.  Or if  the software finds a matching hash on the local disk, it can skip the need to query and download from a remote source without relying on fragile timestamps etc.  There's kinda a proof of principle of this in [contentid](https://github.com/cboettig/contentid), but no higher-level tool that uses content identifiers to implement a 'living dataset' on GitHub or other provider (yet)!

**Comment by maelle** [comment]
Something I stupidly forgot to mention: it might make sense to make a pre-submission inquiry to rOpenSci software peer review, if the package is to be actively maintained (and if it is of interest to you).

**Comment by richfitz** [comment]
I think that traitecoevo with a view to move this, or something like it, into ropensci later.

**Comment by maelle** [comment]
So, should a transfer happen? Thank you. :slightly_smiling_face:

**Comment by maelle** [comment]
(note that it can't be transferred to an account/org where there is a fork of it, so the fork would first need to be deleted/transferred :sweat_smile: )

**Comment by richfitz** [comment]
I have reconciled the histories and moved this to traitecoevo now

**Comment by maelle** [comment]
thank you!!
